### ISSUE TITLE
download models doesn't re-download new versions of models

### ISSUE THREAD

**Issue by db0** [Haidra-Org/horde-worker-reGen#84] opened 2024-01-12 23:54 UTC
If a new version of the model was added to the reference, the download script doesn't compare sha256 to redownload it.

**Comment by tazlin** [comment] 2024-01-13 00:07
Fixed on the niter branch

**Comment by tazlin** [comment] 2024-01-13 00:10
If you are willing/able, confirm the changes work as intended and feel free to merge in https://github.com/Haidra-Org/horde-worker-reGen/pull/85. I am unavailable to check this right now.

**Closed** 2024-01-13 00:27 UTC
